In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("/content/knn_classification_practice.csv")

In [4]:
df.head(2)

   age  annual_income  spending_score  purchased
0   26          31411              23          0
1   19          64020              26          0

In [5]:
X = df.iloc[:,:-1]
y = df['purchased']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [8]:
KNN = KNeighborsClassifier(n_neighbors = 3)
KNN.fit(X_train_scaler , y_train)
y_pred = KNN.predict(X_test_scaler)
accuracy_score(y_test , y_pred)

0.925

In [9]:
df.head(2)

   age  annual_income  spending_score  purchased
0   26          31411              23          0
1   19          64020              26          0

In [10]:
KNN.predict(scaler.transform([[27,300000,25]]))

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([1])

In [70]:
class MeraKNN:

  def __init__(self, n_neighbors):
    self.n_neighbors = n_neighbors
    self.X_train = None
    self.y_train = None

  def fit(self , X_train , y_train):
    self.X_train = np.array(X_train)
    self.y_train = np.array(y_train)

  def predict(self, X_test):
    X_test = np.array(X_test)
    for i in X_test:
      distances = []
      for j in self.X_train:

        distances.append(self.calculate_distance(i,j))

      neighbors = sorted(list(enumerate(distances)),key=lambda x: x[1])
      self.majority_count(neighbors)

  def calculate_distance(self, point_a , point_b):
    return np.linalg.norm(point_a - point_b)

  def majority_count(self,neighbors):
    K_neighbors = neighbors[:self.n_neighbors]
    indices = [i[0] for i in K_neighbors]
    print(self.y_train[indices])

In [75]:
KNN = MeraKNN(3)
KNN.fit(X_train_scaler , y_train)
KNN.predict(X_test_scaler)

[1 1 1]
[1 1 1]
[0 0 0]
[1 0 1]
[0 0 0]
[1 1 1]
[1 1 1]
[0 0 0]
[1 1 1]
[1 1 1]
[0 0 0]
[1 1 1]
[0 0 0]
[1 1 1]
[0 0 0]
[0 0 0]
[1 1 1]
[0 0 0]
[0 1 1]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[1 0 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[0 0 0]
[0 0 0]